import { describe, it, expect, vi } from 'vitest';
import {
  requestRoute,
  loadRouteResult,
  clearRoute,
  getActiveRoute,
  generateRouteRequestJson,
  checkEngineStatus,
  loadLatestStaticRouteResult,
  getRegisteredEngineRoutePairs,
} from './engineBridge';

describe('engineBridge - C Engine File Contract Adapter', () => {
  it('reports engine status indicating routefinder.exe is future source of truth', () => {
    const status = checkEngineStatus();
    expect(status.isCEngineActive).toBe(false);
    expect(status.mode).toBe('DEMO_SIMULATION');
    expect(status.binaryName).toBe('routefinder.exe');
    expect(status.requestFile).toBe('route_request.json');
    expect(status.resultFile).toBe('route_result.json');
    expect(status.warningTitle).toContain('DEMO MODE');
  });

  it('generates a valid route_request.json format string for routefinder.exe', () => {
    const jsonStr = generateRouteRequestJson({ source: 'gate', destination: 'library' });
    const parsed = JSON.parse(jsonStr);
    expect(parsed).toEqual({ source: 'gate', destination: 'library' });
  });

  it('requests route with identical source and destination (0 hops)', async () => {
    const result = await requestRoute({ source: 'gate', destination: 'gate' });
    expect(result.found).toBe(true);
    expect(result.path).toEqual(['gate']);
    expect(result.hops).toBe(0);
    expect(result.isMock).toBe(true);
    expect(getActiveRoute()?.path).toEqual(['gate']);
  });

  it('requests a simulated mock route from mock_route_result.json', async () => {
    const result = await requestRoute({ source: 'gate', destination: 'hostel_north' });
    expect(result.found).toBe(true);
    expect(result.path).toEqual(['gate', 'library', 'cs_dept', 'eng_quad', 'hostel_north']);
    expect(result.hops).toBe(4);
    expect(result.visited).toBe(5);
    expect(result.isMock).toBe(true);
  });

  it('returns found: false when route is not in mock catalog and no custom result is loaded', async () => {
    const result = await requestRoute({ source: 'unconnected_a', destination: 'unconnected_b' });
    expect(result.found).toBe(false);
    expect(result.path).toEqual([]);
    expect(result.message).toContain('No route found');
  });

  it('loads an external route_result.json generated by routefinder.exe and registers it as non-mock', async () => {
    const routeResultJson = JSON.stringify({
      found: true,
      path: ['gate', 'custom_junction', 'sports_arena'],
      source: 'gate',
      destination: 'sports_arena',
      visited: 6,
      hops: 2,
    });

    const loaded = await loadRouteResult(routeResultJson);
    expect(loaded.found).toBe(true);
    expect(loaded.path).toEqual(['gate', 'custom_junction', 'sports_arena']);
    expect(loaded.isMock).toBe(false);
    expect(loaded.visited).toBe(6);

    // Verify subsequent request returns this custom route result instead of mock
    const retrieved = await requestRoute({ source: 'gate', destination: 'sports_arena' });
    expect(retrieved.path).toEqual(['gate', 'custom_junction', 'sports_arena']);
    expect(retrieved.isMock).toBe(false);
  });

  it('loads public/route_result.json via loadLatestStaticRouteResult', async () => {
    const mockData = { found: true, path: ['gate', 'admin', 'cafeteria'] };
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({
        ok: true,
        json: async () => mockData,
      })
    );

    const result = await loadLatestStaticRouteResult();
    expect(result.found).toBe(true);
    expect(result.path).toEqual(['gate', 'admin', 'cafeteria']);
    expect(result.hops).toBe(2);
    expect(result.isNativeC).toBe(true);
  });

  it('throws an error on malformed route_result.json', async () => {
    await expect(loadRouteResult('invalid json string')).rejects.toThrow('Failed to load route_result.json');
    await expect(loadRouteResult({ invalid: 'object' })).rejects.toThrow("missing 'path' array");
  });

  it('clears active route via clearRoute()', async () => {
    await requestRoute({ source: 'gate', destination: 'library' });
    expect(getActiveRoute()).not.toBeNull();

    clearRoute();
    expect(getActiveRoute()).toBeNull();
  });

  it('returns a list of available mock route pairs', () => {
    const pairs = getRegisteredEngineRoutePairs();
    expect(pairs.length).toBeGreaterThan(5);
    expect(pairs.some((p) => p.source === 'gate' && p.destination === 'library')).toBe(true);
  });
});
